### ISSUE TITLE
ClientRequestBuilder cookie surprising behaviour

### ISSUE THREAD

**Issue by adwhit** [actix/actix-web#101]
This might just be my expectations that are wrong, but I expected the `cookie(mycookie)` method on `ClientRequestBuilder` to set the `Cookie` header, but it appears to set the `Set-Cookie` header instead. ( [here](https://github.com/actix/actix-web/blob/master/src/client/request.rs#L526))

If this is intended, I think it should be documented as such and there should be a separate `add_cookie` method or some-such. If this is not intended, it should be fixed (and perhaps a `set_set_cookie` method should be added??)

**Comment by adwhit** [comment]
I should add, it would be nice if there was a simple way (or an example) of how to turn a `Set-Cookie` header from a `ClientResponse` into a `Cookie` header in a `ClientRequest` as I found this pretty hard to work out.

**Comment by fafhrd91** [comment]
this is copy/paste bug

**Comment by fafhrd91** [comment]
fixed in master

`ClientResponse::cookies()` reads SET-COOKIE  header values
`ClientRequestBuilder::cookie()` generates COOKIE header

**Comment by fafhrd91** [comment]
please reopen, you there are other client cookie inconsistencies

**Comment by adwhit** [comment]
Thanks for your quick response, as always.

There is still a problem with the Set-Cookie parsing. Since it splits on `; ` and tries to turn each slice into a cookie, it fails on something like below -
```
Set-Cookie: LSID=DQAAAK…Eaem_vYg; Path=/accounts; Expires=Wed, 13 Jan 2021 22:23:01 GMT; Secure; HttpOnly
```
because it tries to parse `HttpOnly` separately and fails since it is not of form `key=value`.

Of course the correct way to handle is to parse the whole line at once. I am happy to attempt a PR.

**Comment by fafhrd91** [comment]
@adwhit I refactored cookie handling again, could you check if everything works for you?

**Comment by adwhit** [comment]
OK, I'm certainly no expert at HTTP but I tried to figure out what the expected behaviour is.
With the latest master, I ran `cargo test test_client_cookie_handling` and sniffed it with Wireshark.

```
GET / HTTP/1.1
host: 127.0.0.1
accept-encoding: gzip, deflate
cookie: cookie1=value1
cookie: cookie2=value2; HttpOnly; Secure; Path=/; Domain=www.example.org
date: Thu, 08 Mar 2018 11:01:29 GMT
```
This, as I understand, is incorrect for two reasons - first there must only be one Cookie header with each cookie encoded as `key=value; ` (see https://stackoverflow.com/questions/16305814/are-multiple-cookie-headers-allowed-in-an-http-request), and second, the `Secure`, `HttpOnly` etc parts should not be there - they are only for the `Set-Cookie` header.

The reply:
```
HTTP/1.1 200 OK
content-length: 0
set-cookie: cookie2=value2; HttpOnly; Secure; Path=/; Domain=www.example.org
set-cookie: cookie1=value1
date: Thu, 08 Mar 2018 11:01:29 GMT
```
*is* correct, as I understand it (so the server is setting the cookies correctly)

**Comment by fafhrd91** [comment]
Oh crap :)
Ok, I’ll test cookies with python client and server

**Comment by adwhit** [comment]
:+1: If you check out PR #111 again you will see how I attempted to fix the above issues in `client/request.rs` (which got reverted). There may be a better way, however.

**Comment by fafhrd91** [comment]
@adwhit could you check again. i hope i fixed it finally :)

**Comment by adwhit** [comment]
Now getting header:
```
GET / HTTP/1.1
host: 127.0.0.1
accept-encoding: gzip, deflate
cookie: cookie2=value2;cookie1=value1
date: Fri, 09 Mar 2018 09:29:15 GMT
```
This looks pretty much correct, thanks! The final thing is that a close reading of the spec (https://tools.ietf.org/html/rfc6265#section-4.2.1) suggests there should always be a space following the semi-colon. How important is this detail? *shrug*

**Comment by fafhrd91** [comment]
Added spaces. I hope it is done now :)
