### ISSUE TITLE
docs.rs - build failed for 0.6.13

### ISSUE THREAD

**Issue by rofrol** [actix/actix-web#299]
https://docs.rs/crate/actix-web/0.6.12/builds/104837

**Comment by fafhrd91** [comment]
should be fixed by next release

**Comment by rofrol** [comment]
Cool. Thanks.

**Comment by fanzeyi** [comment]
It is still failing in 0.6.13. :/ 

https://docs.rs/crate/actix-web/0.6.13/builds/105314

**Comment by fafhrd91** [comment]
we have #317 
also we can not do anything, it is up to docs.rs to fix failed bbuilds
