### ISSUE TITLE
Websocket Actor stopped method not called when Broken pip error occurs

### ISSUE THREAD

**Issue by cksac** [actix/actix-web#311]
I would like to do some post actions when web-socket session terminated, but if the server is sending message to client and client terminated. I got following error and stopped methods is not being called.

ERROR 2018-06-13T14:00:01Z: actix_web::pipeline: Error occurred during request handling: Broken pipe (os error 32)
ERROR 2018-06-13T14:00:01Z: actix_web::server::h1: Unhandled error: Broken pipe (os error 32)

```toml
[dependencies]
actix = "0.5.8"
actix-web = "0.6.11"
```

```rust
impl Actor for WsSession {
    type Context = ws::WebsocketContext<Self, WsSessionState>;

    fn started(&mut self, ctx: &mut Self::Context) {
         println!("ws actor started");
    }

    fn stopped(&mut self, ctx: &mut Self::Context) {
        println!("ws actor stopped");
        // Do post action, e.g. notify other actors to stop
    }
}
```

**Comment by fafhrd91** [comment]
this is definitely a bug. i'll check.

**Comment by fafhrd91** [comment]
i added extra checks for errors, could test master?

**Comment by cksac** [comment]
@fafhrd91 thanks for checking on this. Tested in master, found that the error seems occurs when client stopped during `send_text`. You can refer to this [gist](https://gist.github.com/cksac/e4da24b66f473f8fe272a9d7392126c8) to reproduce.

**Comment by fafhrd91** [comment]
thanks for detailed example!

should be fixed in master

**Comment by cksac** [comment]
I can still reproduce the issue, is there anything I missed?

**Comment by fafhrd91** [comment]
Do you reproduce the problem with your example?

**Comment by cksac** [comment]
yes

**Comment by fafhrd91** [comment]
Did you enable info log level? Or replace info! with println!

**Comment by cksac** [comment]
I use ```RUST_LOG=info cargo run``` to start the server, the started get printed, but not stopped.

**Comment by cksac** [comment]
@fafhrd91 so you can't reproduce in your side?

**Comment by fafhrd91** [comment]
works for me. what os do you use?

**Comment by ousado** [comment]
just tested this, the fix works on Linux 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux
output:
```
 INFO 2018-07-11T11:39:33Z: actix311: send msg 9998
 INFO 2018-07-11T11:39:33Z: actix311: send msg 9999
ERROR 2018-07-11T11:39:34Z: actix_web::pipeline: Error occurred during request handling: Broken pipe (os error 32)
 INFO 2018-07-11T11:39:34Z: actix311: websocket sesssion ended
ERROR 2018-07-11T11:39:34Z: actix_web::server::h1: Unhandled error1: Broken pipe (os error 32)
```

**Comment by cksac** [comment]
@fafhrd91 I am using macOS High Sierra Version 10.13.5. Tested in Rust Stable and Nightly.
```
 INFO 2018-07-11T13:28:38Z: actix_web::server::srv: Starting 8 http workers
 INFO 2018-07-11T13:28:38Z: actix_web::server::srv: Starting server on http://127.0.0.1:8080
 INFO 2018-07-11T13:28:41Z: actix_example: websocket sesssion started
ERROR 2018-07-11T13:28:42Z: actix_web::pipeline: Error occurred during request handling: Broken pipe (os error 32)
ERROR 2018-07-11T13:28:42Z: actix_web::server::h1: Unhandled error: Broken pipe (os error 32)
```

**Comment by fafhrd91** [comment]
hmm, works for me macOS 10.13.5

**Comment by fafhrd91** [comment]
are you sure you use latest master?

**Comment by cksac** [comment]
@fafhrd91 you are right, works after delete Cargo.lock and rebuild. Before I just use ```cargo clean``` and rebuild...

**Comment by DoumanAsh** [comment]
@cksac You can just use `cargo update` in future
